### ISSUE TITLE
Integers assigned as same object (bug)?

### ISSUE THREAD

**Issue by cdboschen** [pgbovine/OnlinePythonTutor#255]
My understanding is that Python assigns integers in the range of -5 to 255 to the same object as it has a pre-allocated table for these commonly used values, as well as single characters of the alphabet. So x=5 and y =5 will point to the same object (x is y evaluates to True). However new objects will be created for values outside of this range: x = 519, y = 519, x is y evaluates to False. Pythontutor seems to assume all assigned integers inside or outside of this range will resolve to the same object. Bug? 

![image](https://user-images.githubusercontent.com/12041221/49892231-74f8d400-fe16-11e8-9234-7591d40cf0ee.png)

**Comment by pgbovine** [comment]
thanks for the issue report! closed -- added to here:
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md

**Comment by FrozenBob** [comment]
It's actually perfectly normal for those integers to be the same object even in a Python script running in normal, uninstrumented CPython. They get optimized into a single object during bytecode compilation. This doesn't happen in an interactive session because the two lines get compiled into separate code objects when running interactively. (None of this is guaranteed or documented CPython behavior.)
