### ISSUE TITLE
Why aren't strings objects?

### ISSUE THREAD

**Issue by nickeubank** [pgbovine/OnlinePythonTutor#273]
I noticed that in the Python visualizer, strings get put into separate frame variables:

![image](https://user-images.githubusercontent.com/9683693/62370296-59525300-b4f7-11e9-8a66-7c560bfbfee4.png)

But this seems inconsistent with what's going on in Python given `id` behavior:

![image](https://user-images.githubusercontent.com/9683693/62370348-77b84e80-b4f7-11e9-8d59-74940c6568f6.png)

Shouldn't the string become an object with both vars pointing at it? I get the desire to distinguish mutable and immutable types, but maybe that should be a difference in object box coloring or something?

**Comment by pgbovine** [comment]
good question. you can toggle an option at the bottom to render strings on heap as objects:
http://pythontutor.com/visualize.html#code=x%20%3D%20'test'%0Ay%20%3D%20x&cumulative=false&curInstr=2&heapPrimitives=true&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false

[note that for teaching purposes, especially for beginners, id() shouldn't be relied upon since it's an implementation detail of CPython, not part of the language spec; in other words, it doesn't matter whether x and y are separate 'test' objects or aliases to the same one. some other python interpreter could make them separate (or shared) and have the same behavior.]
